apiVersion: v1
items:
- apiVersion: v1
  kind: LimitRange
  metadata:
    creationTimestamp: null
    name: core-resource-limits
  spec:
    limits:
    - max:
        cpu: "2"
        memory: 1Gi
      min:
        cpu: 200m
        memory: 6Mi
      type: Pod
    - default:
        cpu: "2"
        memory: 1Gi
      defaultRequest:
        cpu: "1"
        memory: 1Gi
      max:
        cpu: "2"
        memory: 1Gi
      maxLimitRequestRatio:
        cpu: "10"
      min:
        cpu: 100m
        memory: 4Mi
      type: Container
kind: List
metadata: {}
